# Generated by Django 4.0.4 on 2024-09-20 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='root_accounts/logos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('person_of_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('poc_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('poc_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('accounts', models.ManyToManyField(related_name='root_accounts', to='accounts.account')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_accounts', to='reps.salesrep')),
            ],
            options={
                'verbose_name': 'Root Account',
                'verbose_name_plural': 'Root Accounts',
                'ordering': ['name'],
            },
        ),
    ]
