# Generated by Django 4.0.4 on 2024-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rootaccount_root_category_branchaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootaccount',
            name='accounts',
        ),
        migrations.AddField(
            model_name='rootaccount',
            name='branch_accounts',
            field=models.ManyToManyField(related_name='root_accounts', to='accounts.branchaccount'),
        ),
    ]
