version: '3'
services:
  backend:
    build: ./backend
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"  # Expose Vite's default port
    environment:
      - HOST=0.0.0.0  # Make Vite accessible on all network interfaces
    command: npm run dev -- --host 0.0.0.0  # Ensure Vite is serving on 0.0.0.0

  db:
    image: postgres
    environment:
      POSTGRES_DB: marathon
      POSTGRES_USER: awc
      POSTGRES_PASSWORD: Starbury03
    ports:
      - "5432:5432"
