version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  # Default superuser
      POSTGRES_PASSWORD: postgres_password_here  # Replace with your secure password
      POSTGRES_DB: marathon  # Default database for Django to use
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Custom SQL commands for user setup
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    command: ["/app/entrypoint.sh"]  # Use custom entrypoint script for Django
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet:
