version: '3'
services:
  backend:
    build: ./backend
    container_name: django_app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production  # Use 'production' settings
      - DJANGO_DB_HOST=db        # Set the database host to the 'db' service
      - DJANGO_DB_NAME=marathon  # Set the database name
      - DJANGO_DB_USER=awc       # Set PostgreSQL user
      - DJANGO_DB_PASSWORD=Starbury03  # Set PostgreSQL password

  frontend:
    build: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres
    environment:
      POSTGRES_DB: marathon
      POSTGRES_USER: awc
      POSTGRES_PASSWORD: Starbury03
    ports:
      - "5432:5432"
