version: '3.7'

services:
  backend:
    build: ./backend
    container_name: django_app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env  # Ensure the .env file has the correct environment variables
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy  # Wait for db to pass health check
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
    expose:
      - "5173"
    environment:
      - HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0
    restart: always

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: marathon
      POSTGRES_USER: awc
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password  # Use Docker secret for password
      POSTGRES_INITDB_ARGS: "--username=postgres --pwfile=/run/secrets/postgres_password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    secrets:
      - postgres_password  # Secure handling of the default superuser password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awc"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Map external port 8080 to container port 80
      - "4443:443" # Map external port 4443 to container port 443
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/staticfiles:/app/staticfiles  # Serve static files
      - ./backend/media:/app/media  # Serve media files
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:

secrets:
  postgres_password:
    file: ./postgres_password.txt  # This file should contain your superuser password
