version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    networks:
      - marathon_net
      
  django:
    build: ./backend
    volumes:
      - ./backend:/app
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application  # Use python manage.py runserver for development
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: backend.settings  # Added for settings reference
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - marathon_net

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - marathon_net

networks:
  marathon_net:

volumes:
  postgres_data:
