version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  # Default superuser for PostgreSQL
      POSTGRES_PASSWORD: postgres_password_here  # Replace with a secure password
      POSTGRES_DB: marathon  # Database that Django will use
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization SQL for user setup
    networks:
      - marathon_webnet  # Updated network to match the existing network name

  backend:
    build:
      context: ./backend
    command: ["/app/entrypoint.sh"]  # Custom entrypoint script for migrations and setup
    volumes:
      - ./backend:/app
      - /var/www/marathon_static:/app/staticfiles  # Bind mount for static files
      - /var/www/marathon_media:/app/media  # Bind mount for media files (if applicable)
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"  # Exposing Django on port 8000 internally
    depends_on:
      - db
    networks:
      - marathon_webnet  # Updated network to match the existing network name

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Dockerfile for building the Vite frontend
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - marathon_webnet  # Updated network to match the existing network name
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:

networks:
  marathon_webnet:  # Changed from 'webnet' to 'marathon_webnet' to match the existing Docker network
    external: true  # Add this line if the network was already created externally
