# Generated by Django 5.1.2 on 2024-11-06 05:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('excerpt', models.TextField()),
                ('image_url', models.URLField()),
                ('content_html', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
