# Generated by Django 4.0.4 on 2024-09-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cd_code',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='commission_base',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paid_status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sku_code',
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_code'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.product'),
        ),
    ]
