# Generated by Django 5.1.2 on 2024-11-06 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesrepzipcode',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='reps.salesrep'),
        ),
        migrations.AlterUniqueTogether(
            name='salesrepzipcode',
            unique_together={('sales_rep', 'zip_code')},
        ),
    ]
