# Generated by Django 4.0.4 on 2024-09-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='sales_reps/profile_pics/'),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
