# Generated by Django 5.1.2 on 2024-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0002_salesrep_profile_pic_salesrep_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
